version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-client
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./:/app
      - /app/node_modules
      - ./mcp_config.db:/app/mcp_config.db
    environment:
      - NODE_ENV=development
      - MCP_DB_PATH=./mcp_config.db
      - DEBUG_MODE=true
    command: ["npm", "run", "dev"]

  nginx:
    image: nginx
    container_name: mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    container_name: mcp-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h; do ./certbot-renew.sh; done'"
    depends_on:
      - nginx
